[tool.poetry]
name = "aoc-2023"
version = "0.1.0"
description = ""
authors = ["Rebecca Lovering <lovering810@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
